name: prml-project1
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=2.0
  - matplotlib>=3.9
  - ipykernel
  - jupyter
  - pytorch::pytorch>=2.11
  - pytorch::torchvision>=0.26
  - pytorch::pytorch-cuda=12.6
  - conda-forge::marimo
  - conda-forge::duckdb
  - conda-forge::polars
  - conda-forge::altair
  - conda-forge::openai
  - conda-forge::ruff
